#!/usr/bin/env bash
#
# Regenerate the Homebrew formula for a published release.
#
#   scripts/update-tap.sh v0.2.0 [path-to-tap-checkout]
#
# Reads SHA256SUMS from the GitHub release rather than recomputing it, so the
# formula can never disagree with the artifacts people actually download.
#
# This is deliberately a local script rather than a step in release.yml: pushing
# to a *different* repository from Actions needs a personal access token stored
# as a secret, and a hand-run script is a smaller thing to trust than a
# cross-repo write credential sitting in CI.

set -euo pipefail

REPO="Tripstack-Corp/rmatrix"
TAP_REPO="Tripstack-Corp/homebrew-tap"

tag="${1:-}"
tap_dir="${2:-}"

if [ -z "$tag" ]; then
    echo "usage: $0 <tag> [tap-checkout-dir]" >&2
    echo "example: $0 v0.2.0" >&2
    exit 2
fi
version="${tag#v}"

if [ -z "$tap_dir" ]; then
    tap_dir="$(mktemp -d)/homebrew-tap"
    echo "Cloning $TAP_REPO into $tap_dir"
    gh repo clone "$TAP_REPO" "$tap_dir" -- --quiet
fi

echo "Fetching checksums for $tag"
sums="$(gh release download "$tag" --repo "$REPO" -p SHA256SUMS -O - 2>/dev/null)"
if [ -z "$sums" ]; then
    echo "error: no SHA256SUMS asset on $tag — has the release finished building?" >&2
    exit 1
fi

sha_for() {
    local target="$1" line
    line="$(printf '%s\n' "$sums" | grep -F "rmatrix-${version}-${target}.tar.gz" || true)"
    if [ -z "$line" ]; then
        echo "error: no checksum for $target in $tag" >&2
        exit 1
    fi
    printf '%s\n' "$line" | awk '{print $1}'
}

MAC_ARM="$(sha_for aarch64-apple-darwin)"
MAC_X86="$(sha_for x86_64-apple-darwin)"
LNX_ARM="$(sha_for aarch64-unknown-linux-gnu)"
LNX_X86="$(sha_for x86_64-unknown-linux-gnu)"

mkdir -p "$tap_dir/Formula"

# Follows the conventions already set by spyc.rb in this tap: interpolate
# #{version} into the URLs, and offer a --HEAD build from main.
cat > "$tap_dir/Formula/rmatrix.rb" <<FORMULA
# Generated by scripts/update-tap.sh in ${REPO}. Do not edit by hand.
class Rmatrix < Formula
  desc "Digital rain for modern terminals"
  homepage "https://github.com/${REPO}"
  version "${version}"
  license "MIT"

  # \`brew install --HEAD rmatrix\` builds main from source. Declared before the
  # platform blocks because \`brew audit --strict\` requires that ordering.
  head do
    url "https://github.com/${REPO}.git", branch: "main"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/${REPO}/releases/download/v#{version}/rmatrix-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "${MAC_ARM}"
    end
    on_intel do
      url "https://github.com/${REPO}/releases/download/v#{version}/rmatrix-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "${MAC_X86}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/${REPO}/releases/download/v#{version}/rmatrix-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${LNX_ARM}"
    end
    on_intel do
      url "https://github.com/${REPO}/releases/download/v#{version}/rmatrix-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${LNX_X86}"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "rmatrix"
    end
  end

  test do
    assert_match(/\d+\.\d+\.\d+/, shell_output("#{bin}/rmatrix --version"))
  end
end
FORMULA

echo "Wrote $tap_dir/Formula/rmatrix.rb for ${version}"
echo
echo "Next:"
echo "  cd $tap_dir"
echo "  git add Formula/rmatrix.rb && git commit -m 'rmatrix ${version}' && git push"
