//! Off-thread terminal writer.
//!
//! The simulation must never be held hostage by a slow terminal. `write(2)` on a
//! pty blocks once the emulator falls behind and the kernel buffer fills, and a
//! blocking write on the frame path stalls *everything*: input handling, the
//! clock, the rain. That stall then shows up as a jump in the animation, because
//! the next `dt` covers the whole stall.
//!
//! So the frame path here never touches a file descriptor. The renderer draws
//! into a plain `Vec<u8>` — which cannot block and cannot fail — and the vector
//! is handed to a writer thread that owns stdout.
//!
//! # Why exactly one frame may be in flight
//!
//! Back-pressure has to do *something* when the terminal is behind. Dropping
//! already-generated bytes is not an option: [`crate::render::Renderer`] keeps a
//! `prev` buffer describing what it believes is on screen, so any byte it
//! emitted and we discarded leaves that cell permanently stale — a smear that
//! never repairs itself.
//!
//! The trick is to coalesce *before* generating instead of after. [`acquire`]
//! hands out the single frame buffer only when the writer is idle; while the
//! writer is busy the caller simply does not draw, and keeps simulating. The
//! damage tracker diffs against the last *emitted* state rather than the last
//! *simulated* one, so the next draw naturally emits the union of everything
//! that changed in the meantime, as one frame. Coalescing is therefore free,
//! exact, and impossible to get wrong: no byte the renderer produced is ever
//! discarded, so `prev` always describes the real screen.
//!
//! [`acquire`]: FrameWriter::acquire
//!
//! # Why a thread rather than `O_NONBLOCK`
//!
//! Marking fd 1 non-blocking and queueing in user space was the alternative. It
//! is rejected because `O_NONBLOCK` lives on the *open file description*, which
//! stdout shares with the parent shell and every sibling process on that tty; a
//! crash between setting and clearing it leaves the user's shell with a
//! non-blocking tty, which breaks unrelated programs. A thread keeps the blocking
//! semantics the rest of the world expects.

use std::io::Write;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc::{Receiver, SyncSender, TryRecvError, TrySendError, sync_channel};
use std::time::Duration;

/// Process-wide "stop writing to the terminal" latch.
///
/// It is global rather than owned because the panic hook has to be able to set
/// it and cannot reach into the loop's state. Each writer additionally has its
/// own latch (see [`FrameWriter::shutdown`]); either one suppresses frames.
static PANIC_ABORT: AtomicBool = AtomicBool::new(false);

/// Tell every writer thread to stop emitting frames. Idempotent, and safe to
/// call from a panic hook.
pub fn abort_all() {
    PANIC_ABORT.store(true, Ordering::SeqCst);
}

enum Msg {
    /// One complete frame's worth of bytes. The vector is recycled afterwards.
    Frame(Vec<u8>),
    /// Final bytes (terminal restore), then the thread exits and signals `done`.
    Finish(Vec<u8>),
}

/// The writer thread went away — a write error, or the channel closed. Fatal:
/// the caller must stop drawing, because it can no longer know what the terminal
/// is showing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WriterGone;

impl std::fmt::Display for WriterGone {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("terminal writer stopped")
    }
}

impl std::error::Error for WriterGone {}

/// Handle to the writer thread, plus the single recycled frame buffer.
pub struct FrameWriter {
    tx: Option<SyncSender<Msg>>,
    /// Emptied frame buffers coming back from the writer.
    ret: Receiver<Vec<u8>>,
    done: Receiver<()>,
    /// The one buffer, when it is ours. `None` means a frame is in flight.
    free: Option<Vec<u8>>,
    abort: Arc<AtomicBool>,
    gone: bool,
    submitted: u64,
    coalesced: u64,
}

impl FrameWriter {
    /// Spawn a writer thread owning `out`, with `capacity` bytes reserved for
    /// the frame buffer.
    ///
    /// `out` should be `std::io::stdout()` in production: `Stdout::write_all`
    /// holds the global stdout mutex for the whole call, which is what makes the
    /// teardown path safe — a restore sequence written from the main thread
    /// cannot interleave *inside* a frame, only before or after one.
    pub fn spawn<W: Write + Send + 'static>(out: W, capacity: usize) -> FrameWriter {
        // Capacity 2, but the protocol keeps at most one `Frame` queued (see
        // `acquire`). The spare slot guarantees `Finish` can always be posted
        // without blocking, however far behind the terminal is.
        let (tx, rx) = sync_channel::<Msg>(2);
        let (ret_tx, ret_rx) = sync_channel::<Vec<u8>>(1);
        let (done_tx, done_rx) = sync_channel::<()>(1);
        let abort = Arc::new(AtomicBool::new(false));
        let thread_abort = Arc::clone(&abort);

        // Detached on purpose: the handle is dropped, so teardown never *joins*
        // a thread that might be parked inside a blocking write. It cannot
        // outlive us either — returning from `main` tears the process down.
        #[allow(
            clippy::expect_used,
            reason = "the only sanctioned panic outside tests: spawn fails when \
                      the OS is out of threads, and there is no useful degraded \
                      mode — without a writer nothing can reach the terminal, \
                      and returning an error here would only push the same \
                      abort one frame later with the screen already cleared"
        )]
        std::thread::Builder::new()
            .name("rmatrix-writer".into())
            .spawn(move || pump(out, &rx, &ret_tx, &done_tx, &thread_abort))
            .expect("spawning the writer thread");

        FrameWriter {
            tx: Some(tx),
            ret: ret_rx,
            done: done_rx,
            free: Some(Vec::with_capacity(capacity)),
            abort,
            gone: false,
            submitted: 0,
            coalesced: 0,
        }
    }

    /// The frame buffer, cleared and ready to draw into — or `None` if the
    /// writer is still busy with the previous frame, in which case the caller
    /// must **not** draw. Skipping the draw is what coalesces the frames.
    pub fn acquire(&mut self) -> Option<Vec<u8>> {
        if self.free.is_none() {
            match self.ret.try_recv() {
                Ok(b) => self.free = Some(b),
                Err(TryRecvError::Empty) => {}
                Err(TryRecvError::Disconnected) => self.gone = true,
            }
        }
        match self.free.take() {
            Some(mut b) => {
                b.clear();
                Some(b)
            }
            None => {
                self.coalesced += 1;
                None
            }
        }
    }

    /// Hand a drawn frame to the writer. Never blocks and never discards: an
    /// error means the bytes could not be delivered *and* the caller's damage
    /// state is now untrustworthy, so it must tear down rather than carry on.
    pub fn submit(&mut self, buf: Vec<u8>) -> Result<(), WriterGone> {
        let Some(tx) = self.tx.as_ref() else {
            self.gone = true;
            return Err(WriterGone);
        };
        match tx.try_send(Msg::Frame(buf)) {
            Ok(()) => {
                self.submitted += 1;
                Ok(())
            }
            // `Full` is unreachable while the caller respects `acquire`, but
            // treat it exactly like a dead writer rather than dropping bytes.
            Err(TrySendError::Full(_) | TrySendError::Disconnected(_)) => {
                self.gone = true;
                Err(WriterGone)
            }
        }
    }

    /// True once the writer thread has stopped. The caller should quit.
    #[must_use]
    pub fn failed(&self) -> bool {
        self.gone
    }

    /// Frames actually sent to the terminal.
    #[must_use]
    pub fn submitted(&self) -> u64 {
        self.submitted
    }

    /// Draws skipped because the terminal was behind. These are not lost
    /// updates — the next frame carries their damage too.
    #[must_use]
    pub fn coalesced(&self) -> u64 {
        self.coalesced
    }

    /// Stop the writer, asking it to emit `last` (the terminal-restore
    /// sequence) as its final act.
    ///
    /// Returns `true` if the writer confirmed it wrote `last`, in which case the
    /// caller must not write it again. On `false` the caller should emit it
    /// itself; that write will simply queue behind the wedged one on the stdout
    /// mutex rather than interleaving with it.
    pub fn shutdown(&mut self, last: Vec<u8>, timeout: Duration) -> bool {
        // Any frame not yet started is now pointless — we are leaving the alt
        // screen. This is also what makes quit snappy when the terminal is slow.
        self.abort.store(true, Ordering::SeqCst);
        let Some(tx) = self.tx.take() else {
            return false;
        };
        if tx.try_send(Msg::Finish(last)).is_err() {
            return false;
        }
        self.done.recv_timeout(timeout).is_ok()
    }
}

fn pump<W: Write>(
    mut out: W,
    rx: &Receiver<Msg>,
    ret: &SyncSender<Vec<u8>>,
    done: &SyncSender<()>,
    abort: &AtomicBool,
) {
    while let Ok(msg) = rx.recv() {
        match msg {
            Msg::Frame(mut buf) => {
                if !abort.load(Ordering::Relaxed) && !PANIC_ABORT.load(Ordering::Relaxed) {
                    // This is the call that blocks when the emulator is behind.
                    // It blocks *here*, on this thread, and nothing else waits.
                    if out.write_all(&buf).is_err() || out.flush().is_err() {
                        return;
                    }
                }
                buf.clear();
                if ret.send(buf).is_err() {
                    return;
                }
            }
            Msg::Finish(bytes) => {
                // Restore runs even under abort: those latches suppress rain,
                // not teardown.
                let _ = out.write_all(&bytes);
                let _ = out.flush();
                let _ = done.send(());
                return;
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;
    use std::time::Instant;

    /// A sink that takes `delay` per write, standing in for a terminal that
    /// cannot keep up.
    struct SlowSink {
        log: Arc<Mutex<Vec<u8>>>,
        delay: Duration,
    }

    impl Write for SlowSink {
        fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
            std::thread::sleep(self.delay);
            self.log.lock().expect("log mutex").extend_from_slice(buf);
            Ok(buf.len())
        }
        fn flush(&mut self) -> std::io::Result<()> {
            Ok(())
        }
    }

    fn sink(delay_ms: u64) -> (SlowSink, Arc<Mutex<Vec<u8>>>) {
        let log = Arc::new(Mutex::new(Vec::new()));
        (
            SlowSink {
                log: Arc::clone(&log),
                delay: Duration::from_millis(delay_ms),
            },
            log,
        )
    }

    #[test]
    fn everything_submitted_is_written_in_order() {
        let (s, log) = sink(0);
        let mut fw = FrameWriter::spawn(s, 64);
        let mut expected = Vec::new();
        for i in 0..200u8 {
            // Spin until the buffer comes back: nothing may be skipped here,
            // because we want to prove delivery is lossless and ordered.
            let mut buf = loop {
                if let Some(b) = fw.acquire() {
                    break b;
                }
                std::thread::yield_now();
            };
            buf.extend_from_slice(&[i, i, i]);
            expected.extend_from_slice(&[i, i, i]);
            fw.submit(buf).expect("writer alive");
        }
        // Wait for the last frame to land before quitting: `shutdown` latches
        // abort, which deliberately abandons any frame not yet started.
        while fw.acquire().is_none() {
            std::thread::yield_now();
        }
        assert!(fw.shutdown(Vec::new(), Duration::from_secs(5)));
        assert_eq!(*log.lock().expect("log mutex"), expected);
    }

    #[test]
    fn a_slow_sink_coalesces_instead_of_blocking_the_caller() {
        let (s, _log) = sink(50);
        let mut fw = FrameWriter::spawn(s, 64);
        let start = Instant::now();
        // 40 ticks at ~1ms each. Blocked, that would be 40 x 51ms; decoupled it
        // is 40 x 1ms. The threshold sits an order of magnitude clear of both,
        // so a loaded CI machine cannot tip it either way.
        for _ in 0..40 {
            if let Some(mut b) = fw.acquire() {
                b.push(b'x');
                fw.submit(b).expect("writer alive");
            }
            std::thread::sleep(Duration::from_millis(1));
        }
        let elapsed = start.elapsed();
        assert!(
            elapsed < Duration::from_millis(400),
            "the caller was blocked by the sink: {elapsed:?}"
        );
        assert!(
            fw.coalesced() > 20,
            "expected most ticks to coalesce, got {}",
            fw.coalesced()
        );
        assert!(fw.submitted() >= 1);
        fw.shutdown(Vec::new(), Duration::from_secs(5));
    }

    #[test]
    fn at_most_one_frame_is_ever_in_flight() {
        let (s, _log) = sink(5);
        let mut fw = FrameWriter::spawn(s, 64);
        for _ in 0..50 {
            if let Some(mut b) = fw.acquire() {
                // Holding the buffer means nothing else can be outstanding.
                assert!(
                    fw.acquire().is_none(),
                    "handed out a second buffer while one was live"
                );
                b.push(b'y');
                fw.submit(b).expect("writer alive");
            }
            std::thread::sleep(Duration::from_millis(1));
        }
        fw.shutdown(Vec::new(), Duration::from_secs(5));
    }

    #[test]
    fn shutdown_emits_the_restore_sequence_last() {
        let (s, log) = sink(0);
        let mut fw = FrameWriter::spawn(s, 64);
        let mut b = fw.acquire().expect("first buffer is free");
        b.extend_from_slice(b"frame");
        fw.submit(b).expect("writer alive");
        assert!(fw.shutdown(b"RESTORE".to_vec(), Duration::from_secs(5)));
        let got = log.lock().expect("log mutex").clone();
        assert!(got.ends_with(b"RESTORE"), "restore was not last: {got:?}");
    }

    #[test]
    fn shutdown_still_restores_when_frames_are_being_dropped() {
        let (s, log) = sink(30);
        let mut fw = FrameWriter::spawn(s, 64);
        let b = fw.acquire().expect("free");
        fw.submit(b).expect("alive");
        // shutdown latches abort, so any queued frame is skipped, but the
        // restore must still land.
        assert!(fw.shutdown(b"RESTORE".to_vec(), Duration::from_secs(5)));
        assert!(log.lock().expect("log mutex").ends_with(b"RESTORE"));
    }

    #[test]
    fn a_dead_writer_is_reported_rather_than_silently_dropping_bytes() {
        struct Broken;
        impl Write for Broken {
            fn write(&mut self, _: &[u8]) -> std::io::Result<usize> {
                Err(std::io::Error::other("gone"))
            }
            fn flush(&mut self) -> std::io::Result<()> {
                Ok(())
            }
        }
        let mut fw = FrameWriter::spawn(Broken, 64);
        let mut b = fw.acquire().expect("free");
        b.extend_from_slice(b"frame"); // `write_all` on an empty slice never fails
        fw.submit(b).expect("first submit reaches the thread");
        // The thread dies on the failed write; the caller must notice rather
        // than assume its damage state still matches the screen.
        let deadline = Instant::now() + Duration::from_secs(5);
        while !fw.failed() && Instant::now() < deadline {
            let _ = fw.acquire();
            std::thread::sleep(Duration::from_millis(1));
        }
        assert!(fw.failed(), "a dead writer went unnoticed");
    }
}
